# Generated by Django 6.1.1 on 2026-10-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='房間名稱')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='房間代碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '麻將房間',
                'verbose_name_plural': '麻將房間',
                'ordering': ('-created_at',),
            },
        ),
    ]
